#!/usr/bin/env node
// =============================================================================
// scripts/bake.mjs — bake real model embeddings for the emoji vocabulary.
//
// Embeds each glyph's `buildEmojiEmbeddingText(...)` through an embeddings model
// ONCE and writes src/baked.data.js, turning the deterministic fallback space
// into a semantic one (🍺 ≈ 🍻, ⛳ distinct) that ships static + works offline.
//
// Usage:
//   OPENAI_API_KEY=sk-... node scripts/bake.mjs
//   node scripts/bake.mjs --emojis "🍺🍻⛳🔥📍👬🎸" --dimensions 256 --model text-embedding-3-small
//
// Provider-agnostic by shape: any endpoint returning {data:[{index,embedding}]}.
// =============================================================================
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import {
  buildEmojiEmbeddingText,
  DEFAULT_EMOJIS,
  normalizeVector,
} from '../src/index.js';
import { centerTable } from '../src/center.js';
import { quantizeTable } from '../src/quantize.js';

const arg = (flag, fallback) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};
const has = (flag) => process.argv.includes(flag);

const ENDPOINT = arg('--endpoint', 'https://api.openai.com/v1/embeddings');
const MODEL = arg('--model', 'text-embedding-3-small');
const DIMENSIONS = Number(arg('--dimensions', '256'));
const BATCH = Number(arg('--batch', '1000'));
const QUANTIZE = arg('--quantize', '') === 'int8';
const API_KEY = process.env.OPENAI_API_KEY || arg('--api-key', '');
const OUT = fileURLToPath(new URL('../src/baked.data.js', import.meta.url));

// Dependency-free enumeration of the emoji vocabulary via the Unicode
// Extended_Pictographic property over the blocks emoji actually live in.
const enumerateEmoji = () => {
  const out = new Set();
  const ranges = [
    [0x1f000, 0x1faff], [0x1f900, 0x1f9ff], [0x2600, 0x27bf],
    [0x2300, 0x23ff], [0x2b00, 0x2bff], [0x2190, 0x21ff], [0x25a0, 0x25ff],
  ];
  for (const [start, end] of ranges) {
    for (let cp = start; cp <= end; cp += 1) {
      const ch = String.fromCodePoint(cp);
      if (/\p{Extended_Pictographic}/u.test(ch)) out.add(ch);
    }
  }
  return [...out];
};

const emojisArg = arg('--emojis', '');
const EMOJIS = emojisArg
  ? Array.from(
      new Intl.Segmenter('en', { granularity: 'grapheme' }).segment(emojisArg),
      (p) => p.segment
    ).filter((p) => p.trim())
  : has('--all-emoji')
    ? enumerateEmoji()
    : [...DEFAULT_EMOJIS];

const fail = (message) => {
  console.error(`✗ ${message}`);
  process.exit(1);
};

if (!API_KEY) {
  fail('No API key. Set OPENAI_API_KEY (or pass --api-key). Nothing was written.');
}

const embedBatch = async (chunk) => {
  const response = await fetch(ENDPOINT, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: MODEL,
      input: chunk.map((emoji) => buildEmojiEmbeddingText(emoji)),
      dimensions: DIMENSIONS,
    }),
  });
  if (!response.ok) {
    fail(`embeddings API ${response.status}: ${(await response.text()).slice(0, 300)}`);
  }
  const data = await response.json();
  return {
    model: data?.model || MODEL,
    vectors: (data?.data || [])
      .slice()
      .sort((l, r) => l.index - r.index)
      .map((item) => item.embedding),
  };
};

console.log(
  `▸ baking ${EMOJIS.length} emojis · ${MODEL} · ${DIMENSIONS}-d` +
    `${QUANTIZE ? ' · int8' : ''} · batch ${BATCH}`
);

const ordered = [];
let resolvedModel = MODEL;
for (let i = 0; i < EMOJIS.length; i += BATCH) {
  const chunk = EMOJIS.slice(i, i + BATCH);
  console.log(`  batch ${Math.floor(i / BATCH) + 1} (${chunk.length})`);
  const { model, vectors } = await embedBatch(chunk);
  resolvedModel = model;
  ordered.push(...vectors);
}

if (ordered.length !== EMOJIS.length) {
  fail(`expected ${EMOJIS.length} vectors, got ${ordered.length}`);
}

const vectors = {};
EMOJIS.forEach((emoji, i) => {
  vectors[emoji] = normalizeVector(ordered[i]).map((v) => Number(v.toFixed(6)));
});

let table = {
  provider: 'openai',
  model: resolvedModel,
  dimensions: ordered[0]?.length || DIMENSIONS,
  builtAt: new Date().toISOString(),
  vectors,
};
// Center by default (spreads the compressed similarity band); --no-center opts out.
if (!has('--no-center')) table = centerTable(table);
if (QUANTIZE) table = quantizeTable(table);

const file = `// AUTO-GENERATED by \`npm run bake\` (scripts/bake.mjs). Do not edit by hand.
export const BAKED = ${JSON.stringify(table, null, 2)};
`;

await writeFile(OUT, file, 'utf8');
console.log(`✓ wrote ${Object.keys(vectors).length} vectors → src/baked.data.js`);
