#!/usr/bin/env node
// =============================================================================
// scripts/build-names.mjs — generate src/names.data.js (emoji → {name, group}).
//
// The GLOBAL meaning layer: every emoji's canonical CLDR name + group, from the
// unicode-emoji-json dataset. Small + tree-shakeable (display), and it enriches
// the embedding text so the vectors are semantic for the whole vocabulary.
// App-SPECIFIC bindings (🍺 → "bar") stay in the consuming app, not here.
//
// Reads data/emoji-source.json; fetches it once if absent (no npm dep needed).
//   node scripts/build-names.mjs
// =============================================================================
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const SOURCE_URL =
  'https://unpkg.com/unicode-emoji-json@0.8.0/data-by-emoji.json';
const SRC = fileURLToPath(new URL('../data/emoji-source.json', import.meta.url));
const OUT = fileURLToPath(new URL('../src/names.data.js', import.meta.url));

let raw;
try {
  raw = JSON.parse(await readFile(SRC, 'utf8'));
} catch {
  console.log(`▸ fetching ${SOURCE_URL}`);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    console.error(`✗ fetch failed (${res.status})`);
    process.exit(1);
  }
  raw = await res.json();
  await mkdir(fileURLToPath(new URL('../data', import.meta.url)), {
    recursive: true,
  });
  await writeFile(SRC, JSON.stringify(raw), 'utf8');
}

const names = {};
for (const [glyph, meta] of Object.entries(raw)) {
  if (meta?.name) names[glyph] = { name: meta.name, group: meta.group || '' };
}

const file =
  '// AUTO-GENERATED by scripts/build-names.mjs (unicode-emoji-json). Do not edit.\n' +
  `export const EMOJI_NAMES = ${JSON.stringify(names)};\n`;
await writeFile(OUT, file, 'utf8');
console.log(`✓ wrote ${Object.keys(names).length} names → src/names.data.js`);
