#!/usr/bin/env node
// =============================================================================
// scripts/build-unicode.mjs — universal Unicode name data from the UCD.
//
// Parses UnicodeData.txt (the canonical source) into two artifacts:
//   • src/unicode-ranges.data.js — the ALGORITHMIC ranges [first, last, prefix].
//     ~120k chars (CJK, Hangul, Tangut, …) whose names come from a RULE, so they
//     cost zero storage. Small + bundled.
//   • src/unicode-names.data.js  — the ~40k EXPLICITLY-named chars (hex → name).
//     The big table; lazy-loaded, never eagerly bundled.
//
// This is the "optimize given 1,114,112 code points" move: store only what can't
// be derived. Reproducible via `npm run build-unicode` (fetches the UCD if absent).
// =============================================================================
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const UCD_URL = 'https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt';
const SRC = fileURLToPath(new URL('../data/UnicodeData.txt', import.meta.url));
const NAMES_OUT = fileURLToPath(
  new URL('../src/unicode-names.data.js', import.meta.url)
);
const RANGES_OUT = fileURLToPath(
  new URL('../src/unicode-ranges.data.js', import.meta.url)
);

let text;
try {
  text = await readFile(SRC, 'utf8');
} catch {
  console.log(`▸ fetching ${UCD_URL}`);
  const res = await fetch(UCD_URL);
  if (!res.ok) {
    console.error(`✗ fetch failed (${res.status})`);
    process.exit(1);
  }
  text = await res.text();
  await mkdir(fileURLToPath(new URL('../data', import.meta.url)), {
    recursive: true,
  });
  await writeFile(SRC, text, 'utf8');
}

// Map a UnicodeData range marker → the canonical derived-name prefix (UAX #44).
// 'HANGUL SYLLABLE' is special — derived from its L/V/T jamo in the resolver.
const rangePrefix = (marker) => {
  const m = marker.toLowerCase();
  if (m.includes('cjk compatibility ideograph')) return 'CJK COMPATIBILITY IDEOGRAPH';
  if (m.includes('cjk ideograph')) return 'CJK UNIFIED IDEOGRAPH';
  if (m.includes('tangut ideograph')) return 'TANGUT IDEOGRAPH';
  if (m.includes('khitan small script')) return 'KHITAN SMALL SCRIPT CHARACTER';
  if (m.includes('nushu character')) return 'NUSHU CHARACTER';
  if (m.includes('hangul syllable')) return 'HANGUL SYLLABLE';
  if (m.includes('private use')) return 'PRIVATE USE';
  return marker.toUpperCase();
};

const lines = text.trim().split('\n');
const names = {};
const ranges = [];
for (let i = 0; i < lines.length; i += 1) {
  const fields = lines[i].split(';');
  const code = fields[0];
  const name = fields[1];
  if (name.endsWith(', First>')) {
    const last = lines[(i += 1)].split(';');
    ranges.push([
      parseInt(code, 16),
      parseInt(last[0], 16),
      rangePrefix(name.replace(/^</, '').replace(/, First>$/, '')),
    ]);
  } else if (name.startsWith('<')) {
    // control/unnamed (e.g. <control>) — no stored name; derived if ever needed.
  } else {
    names[code] = name;
  }
}

await writeFile(
  RANGES_OUT,
  '// AUTO-GENERATED by scripts/build-unicode.mjs (UCD). [firstCp, lastCp, prefix].\n' +
    `export const UNICODE_RANGES = ${JSON.stringify(ranges)};\n`,
  'utf8'
);
await writeFile(
  NAMES_OUT,
  '// AUTO-GENERATED by scripts/build-unicode.mjs (UCD UnicodeData.txt). Lazy-loaded.\n' +
    `export const UNICODE_NAMES = ${JSON.stringify(names)};\n`,
  'utf8'
);
console.log(
  `✓ ${Object.keys(names).length} explicit names + ${ranges.length} algorithmic ranges`
);
